export const GET_INDEX_VALUES = 'GET_INDEX_VALUES';
export const GET_CONTROLPANEL_FALLBACKS = 'GET_CONTROLPANEL_FALLBACKS';

export const CREATE_ATTACHMENT = 'CREATE_ATTACHMENT';
export const GET_ALL_ATTACHMENTS = 'GET_ALL_ATTACHMENTS';
export const GET_ATTACHMENTS = 'GET_ATTACHMENTS';
export const UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT';
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';

export const GET_PORTLETS = 'GET_PORTLETS';
